# Generated by Django 4.2.20 on 2025-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0085_squashed_0191_remove_profile_typo_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='forbidden_leave',
            field=models.BooleanField(default=False, verbose_name='forbidden leave'),
        ),
    ]
