# Generated by Django 4.2.16 on 2025-07-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0193_alter_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If the organization is hidden, users cannot see the organization.', verbose_name='is hidden'),
        ),
    ]
