# Generated by Django 4.2.16 on 2025-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0194_organization_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='delay_contest',
            field=models.BooleanField(default=False, help_text='If true, all submissions will be delayed by 1 minute.', verbose_name='delay contest'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='forbidden_leave',
            field=models.BooleanField(default=False, help_text='If true, users will not be able to leave the contest while it is running. (beta)', verbose_name='forbidden to leave'),
        ),
    ]
